### ISSUE TITLE
2.0.0 package does not have a nuget dependency on NServiceBus [6,7) to identify in the package manager for which NServiceBus version it is

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.Metrics.ServiceControl#13]
![image](https://user-images.githubusercontent.com/152998/33462893-a93651ca-d63a-11e7-837f-ff30e47c7a08.png)

**Comment by WilliamBZA** [comment]
NServiceBus.Metrics has the dependency on NServiceBus, so NServiceBus.Metrics.ServiceControl has a transitive dependency on NServiceBus

**Comment by Scooletz** [comment]
☝️ What @WilliamBZA said . @ramonsmits close it if you find this answer valid.

**Comment by ramonsmits** [comment]
@WilliamBZA @Scooletz Correct, but it is needed to identify for which NServiceBus version the package is to the user. So this is needed from a usability perspective.

**Comment by Scooletz** [comment]
> So this is needed from a usability perspective.

Closing up transitive dependencies for any reason is not the way to go.

**Comment by Scooletz** [comment]
No comments since my last one. Closing.

**Comment by ramonsmits** [comment]
> If you install NSB first, then nuspec ranges will guide you to install the correct version.

That is not my experience, when you add an additional package it by default tries to install the latest version and tries to update NServiceBus to a newer version at the same time.

**Comment by Scooletz** [comment]
Will review in a few hours.

**Comment by bording** [comment]
One thing I have noticed that complicates doing these sort of comparisons is the fact the we currently have prerelease packages that have prerelease versions in the version ranges of the dependencies.

For example, if you've got a package that has a dependency with a range of `[1.0.0, 2.0.0)` you can install a `2.0.0-beta0012` version of that package and it will be considered to not violate it because `2.0.0-beta0012` < `2.0.0`.

Once we get to final packages, then this goes away, and you get warnings/errors about being outside of the package range.

**Comment by Scooletz** [comment]
Interesting finding @bording . Do you know what approach do we use for the rest? Just waiting for the final bits?

**Comment by Scooletz** [comment]
Closing as the result of the last comment

**Comment by ramonsmits** [comment]
I'm reopening this as it really must be made clear in the package for what version of NServiceBus the package is. I had to *again* trail and error before discovering the right NServiceBus version.

If you do not want to add the dependency which would be most obvious then please considere to add the aligned dependency to the package Description

**Comment by dvdstelt** [comment]
> That is not my experience, when you add an additional package it by default tries to install the latest version and tries to update NServiceBus to a newer version at the same time.

I don't understand this? It tries to update to `NServiceBus 6.4.3` (which is latest version atm) but not to higher versions?

**Comment by ramonsmits** [comment]
Ok, had this issue *again* NServiceBus version isn't visible on the package so for fun I just decided to install the latest version to see what happens and as you can see it installed NServiceBus 7, while that is not what it should have done.

I just want to add metrics to my existing NServiceBus 6 project and for that reason it must be clear in the package dependencies for which NServiceBus version the package is so that you don't have this situation where I now have to revert all changes.......

```
Attempting to gather dependency information for package 'NServiceBus.Metrics.ServiceControl.3.0.0-beta0002' with respect to project 'Hosts\NServiceBus6', targeting '.NETFramework,Version=v4.5.2'
Gathering dependency information took 1,39 sec
Attempting to resolve dependencies for package 'NServiceBus.Metrics.ServiceControl.3.0.0-beta0002' with DependencyBehavior 'HighestMinor'
Resolving dependency information took 0 ms
Resolving actions to install package 'NServiceBus.Metrics.ServiceControl.3.0.0-beta0002'
Resolved actions to install package 'NServiceBus.Metrics.ServiceControl.3.0.0-beta0002'
Retrieving package 'NServiceBus 7.0.0-beta0013' from 'particular myget.org'.
Retrieving package 'NServiceBus.Metrics 3.0.0-rc0003' from 'nuget.org'.
Retrieving package 'NServiceBus.Metrics.ServiceControl 3.0.0-beta0002' from 'nuget.org'.
  GET https://api.nuget.org/v3-flatcontainer/nservicebus.metrics/3.0.0-rc0003/nservicebus.metrics.3.0.0-rc0003.nupkg
  GET https://www.myget.org/F/particular/api/v2/package/NServiceBus/7.0.0-beta0013
  GET https://api.nuget.org/v3-flatcontainer/nservicebus.metrics.servicecontrol/3.0.0-beta0002/nservicebus.metrics.servicecontrol.3.0.0-beta0002.nupkg
Removed package 'NServiceBus.6.4.1' from 'packages.config'
Successfully uninstalled 'NServiceBus.6.4.1' from NServiceBus6
  OK https://api.nuget.org/v3-flatcontainer/nservicebus.metrics.servicecontrol/3.0.0-beta0002/nservicebus.metrics.servicecontrol.3.0.0-beta0002.nupkg 451ms
Installing NServiceBus.Metrics.ServiceControl 3.0.0-beta0002.
  OK https://api.nuget.org/v3-flatcontainer/nservicebus.metrics/3.0.0-rc0003/nservicebus.metrics.3.0.0-rc0003.nupkg 459ms
Installing NServiceBus.Metrics 3.0.0-rc0003.
  OK https://www.myget.org/F/particular/api/v2/package/NServiceBus/7.0.0-beta0013 582ms
Installing NServiceBus 7.0.0-beta0013.
Adding package 'NServiceBus.7.0.0-beta0013' to folder 'C:\Users\Ramon\src\particular\EndToEnd\packages'
Added package 'NServiceBus.7.0.0-beta0013' to folder 'C:\Users\Ramon\src\particular\EndToEnd\packages'
Added package 'NServiceBus.7.0.0-beta0013' to 'packages.config'
Executing script file 'C:\Users\Ramon\src\particular\EndToEnd\packages\NServiceBus.7.0.0-beta0013\tools\init.ps1'...
Type 'get-help about_NServiceBus' to see all available NServiceBus commands.
Successfully installed 'NServiceBus 7.0.0-beta0013' to NServiceBus6
Adding package 'NServiceBus.Metrics.3.0.0-rc0003' to folder 'C:\Users\Ramon\src\particular\EndToEnd\packages'
Added package 'NServiceBus.Metrics.3.0.0-rc0003' to folder 'C:\Users\Ramon\src\particular\EndToEnd\packages'
Added package 'NServiceBus.Metrics.3.0.0-rc0003' to 'packages.config'
Successfully installed 'NServiceBus.Metrics 3.0.0-rc0003' to NServiceBus6
Adding package 'NServiceBus.Metrics.ServiceControl.3.0.0-beta0002' to folder 'C:\Users\Ramon\src\particular\EndToEnd\packages'
Added package 'NServiceBus.Metrics.ServiceControl.3.0.0-beta0002' to folder 'C:\Users\Ramon\src\particular\EndToEnd\packages'
Added package 'NServiceBus.Metrics.ServiceControl.3.0.0-beta0002' to 'packages.config'
Successfully installed 'NServiceBus.Metrics.ServiceControl 3.0.0-beta0002' to NServiceBus6
Executing nuget actions took 6,74 sec
Time Elapsed: 00:00:08.4168155
========== Finished ==========
```

**Comment by Scooletz** [comment]
I see that you had this problem. Still, I think that @bording comments was the best answer

> Once we get to final packages, then this goes away, and you get warnings/errors about being outside of the package range.

Also, this is a related  NuGet issue https://github.com/NuGet/Home/issues/6434

**Comment by ramonsmits** [comment]
The linked nuget issue doesn't have anything to do with this. To verify this I tried to do the same by adding package 2.0.0 to an NServiceBus 5 solution and the same thing happened as it was upgraded to NServiceBus 6 which is obviously not what you want.

```
Attempting to gather dependency information for package 'NServiceBus.Metrics.ServiceControl.2.0.0' with respect to project 'Hosts\NServiceBus5', targeting '.NETFramework,Version=v4.5.2'
Gathering dependency information took 1,19 sec
Attempting to resolve dependencies for package 'NServiceBus.Metrics.ServiceControl.2.0.0' with DependencyBehavior 'HighestMinor'
Resolving dependency information took 0 ms
Resolving actions to install package 'NServiceBus.Metrics.ServiceControl.2.0.0'
Resolved actions to install package 'NServiceBus.Metrics.ServiceControl.2.0.0'
Retrieving package 'NServiceBus 6.4.3' from 'nuget.org'.
  GET https://api.nuget.org/v3-flatcontainer/nservicebus/6.4.3/nservicebus.6.4.3.nupkg
Found package 'NServiceBus.Log4Net 2.0.0' in 'C:\Users\Ramon\src\particular\EndToEnd\packages'.
Found package 'NServiceBus.Metrics 2.0.0' in 'C:\Users\Ramon\src\particular\EndToEnd\packages'.
Found package 'NServiceBus.Metrics.ServiceControl 2.0.0' in 'C:\Users\Ramon\src\particular\EndToEnd\packages'.
Removed package 'NServiceBus.5.2.24' from 'packages.config'
Successfully uninstalled 'NServiceBus.5.2.24' from NServiceBus5
Removed package 'NServiceBus.Log4Net.1.0.0' from 'packages.config'
Successfully uninstalled 'NServiceBus.Log4Net.1.0.0' from NServiceBus5
  OK https://api.nuget.org/v3-flatcontainer/nservicebus/6.4.3/nservicebus.6.4.3.nupkg 441ms
Installing NServiceBus 6.4.3.
Adding package 'NServiceBus.6.4.3' to folder 'C:\Users\Ramon\src\particular\EndToEnd\packages'
Added package 'NServiceBus.6.4.3' to folder 'C:\Users\Ramon\src\particular\EndToEnd\packages'
Added package 'NServiceBus.6.4.3' to 'packages.config'
Executing script file 'C:\Users\Ramon\src\particular\EndToEnd\packages\NServiceBus.6.4.3\tools\init.ps1'...
Successfully installed 'NServiceBus 6.4.3' to NServiceBus5
Package 'NServiceBus.Log4Net.2.0.0' already exists in folder 'C:\Users\Ramon\src\particular\EndToEnd\packages'
Added package 'NServiceBus.Log4Net.2.0.0' to 'packages.config'
Successfully installed 'NServiceBus.Log4Net 2.0.0' to NServiceBus5
Package 'NServiceBus.Metrics.2.0.0' already exists in folder 'C:\Users\Ramon\src\particular\EndToEnd\packages'
Added package 'NServiceBus.Metrics.2.0.0' to 'packages.config'
Successfully installed 'NServiceBus.Metrics 2.0.0' to NServiceBus5
Package 'NServiceBus.Metrics.ServiceControl.2.0.0' already exists in folder 'C:\Users\Ramon\src\particular\EndToEnd\packages'
Added package 'NServiceBus.Metrics.ServiceControl.2.0.0' to 'packages.config'
Successfully installed 'NServiceBus.Metrics.ServiceControl 2.0.0' to NServiceBus5
Removing package 'NServiceBus.Log4Net.1.0.0' from folder 'C:\Users\Ramon\src\particular\EndToEnd\packages'
Removed package 'NServiceBus.Log4Net.1.0.0' from folder 'C:\Users\Ramon\src\particular\EndToEnd\packages'
Executing nuget actions took 4,36 sec
Time Elapsed: 00:00:06.4477785
========== Finished ==========
```

**Comment by bording** [comment]
@ramonsmits The behavior varies based on which project/package format you're using.

Test scenario: With a new console app, use the VS NuGet UI to install NServiceBus 5.2.5 and then try to install NServiceBus.Metrics.ServiceControl 2.0.0.

#### SDK-style csproj w/PackageReferences
A package downgrade is detected during install and the changes are rolled back. If I instead manually add the PackageReference to the project file instead of using the UI, I get a warning and an error about the package downgrade, so the project fails to build.

#### Classic csproj w/packages.config
NServiceBus is upgraded to 6.2.0 and installation is successful.

#### Classic csproj w/PackageReferences:
NServiceBus.Metrics.ServiceControl is installed, but it leaves NSB 5.2.25 installed as well. There are two warnings that there is a problem, so they don't prevent the project from building.

---

So the best behavior for this scenario is definitely the new project format, since it prevents the installation. However, even if NServiceBus.Metrics.ServiceControl had a direct reference to NServiceBus instead of it being transitive through the NServiceBus.Metrics package, the above behavior would be identical. In some cases you'd get a failure, and in others the package would be upgraded.

**Comment by Scooletz** [comment]
@ramonsmits I'm closing this issue as it is, because it's not the package responsibility to address it, its nuget's.
