### ISSUE TITLE
v1 is incorrectly targeting .net framework 4.5.2, should be 4.5 aligned with core v5

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.Metrics.ServiceControl#16]
A customer that targets .net framework 4.5 with NServiceBus 5 cannot use NServiceBus.Metrics.ServiceControl as it targets 4.5.2

**Comment by Scooletz** [comment]
I checked this requirement. It's correct as this can be seen in the support branch for the core. 
https://github.com/Particular/NServiceBus/blob/support-5.2/src/NServiceBus.Core/NServiceBus.Core.csproj#L12

Will fix.

**Comment by Scooletz** [comment]
Fixed with #17
