### ISSUE TITLE
Prepare release of 1.0

### ISSUE THREAD

**Issue by Scooletz** [Particular/NServiceBus.Metrics.ServiceControl#2]
This issue about preparing the release of v1 of this package that shorly will be followed up with next two versions: 2.0 (targeting NSB.Metrics 2.0) and 3.0 (targeting NSB.Metrics 3.0).

PoA:
- ensure that there are docs (version 1.0 is for the core v5)
- a sample of integration and sending to SC.Monitoring
- align with `SC.Monitoring` to the date of the official release
- make reporting to SC.Monitoring a separate component for doco purposes with the following lifecycle:

|NSB Version | NSB.Metrics version | Component location|
|---|---|---|
| 5 | - | NSB.Metrics.ServiceControl 1.* |
| 6 | 1.* | NSB.Metrics 1.* |
| 6 | 2.* | NSB.Metrics.ServiceControl 2.* |
| 7 | 3.* | NSB.Metrics.ServiceControl 3.* |

**Comment by seanfarmar** [comment]
- [ ] Ask docs maintainers (and servicepulse maintainers and maybe servicecontrol maintainers) where do we put documentation for this

Docs summary: 
> This is a components that enables data to [v6 add metrics data] be sent to ServiceControl.Monitoring, so we can see this data in ServicePulse.

> To add this functionality to an endpoint we need to configure it like this:
`snippet`

**Comment by seanfarmar** [comment]
- [ ] Create component name in docs (metrics_sc): https://github.com/Particular/docs.particular.net/blob/master/components/components.yaml

- [ ] Add an md file in https://github.com/Particular/docs.particular.net/tree/master/nservicebus/operations

- [ ] Create a components directory in snippets (metrics_sc): https://github.com/Particular/docs.particular.net/tree/master/Snippets

- [ ] Create snippets for versions mentioned above (3 versions)
