### ISSUE TITLE
Compatibility issue with NServicebus 7.* with NserviceBus.Metrics and NServiceBus.Metrics.ServiceControl

### ISSUE THREAD

**Issue by hugovlc** [Particular/NServiceBus.Metrics.ServiceControl#38]
I am upgrading NSB 6 to 7 and I use the Metrics 2.* . So I had to update the metrics to 3.0 in order to work with NSB 7 (not compatible with version 6). Now the issue is that there is not a version compatible for NServiceBus.Metrics.ServiceControl (current only NServiceBus.Metrics (>= 2.0.0 && < 3.0.0)) 

When is planed a compatible version?

**Comment by tmasternak** [comment]
@hugovlc we are working on the `NServicebus.Metrics.ServiceControl` targeting Core v7. I'll update you when it's on nuget.

**Comment by tmasternak** [comment]
Version 3.0.1 is out https://www.nuget.org/packages/NServiceBus.Metrics.ServiceControl/3.0.1

**Comment by tmasternak** [comment]
@hugovlc I'm closing this one. If you have any more questions feel free to re-open.

**Comment by hugovlc** [comment]
Thanks
