### ISSUE TITLE
Monitoring fails for ASQ endpoints with non-json serialization

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/NServiceBus.Metrics.ServiceControl#53]
The ASQ transport uses a serializer to create message envelopes as ASQ does not support headers. 

The monitoring instance is expecting json-serialized message envelopes.

If a serializer other than json is used in the endpoint then the monitoring instance cannot deserialize any monitoring messages it is sent.

**Comment by boblangley** [comment]
I am closing this. ASQ conforms to the serializer used by the endpoint, and the problem would not be resolved in this package. This is a problem with Monitoring's lack of configuration for serialization configuration. The most likely workaround at this time is by using a ServiceControl Transport Adapter.

**Comment by udidahan** [comment]
Has a different bug/issue for the platform been raised instead?
