### ISSUE TITLE
ASQ requires escaping monitoring queue name

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/NServiceBus.Metrics.ServiceControl#54]
When using the ASQ transport, user is required to manually escape characters in the monitoring queue name. i.e. if the monitoring queue name is _Particular.Monitoring_ then it must be changed to _Particular-Monitoring_ as the period character (.) is not allowed.

**Comment by boblangley** [comment]
I am closing this as ASQ users already have to use ASQ compliant queue names and are used to the required escaping.
