### ISSUE TITLE
Plugin not sending metric data to ServiceControl

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus.Metrics.ServiceControl#67]
## Symptoms

* Endpoint metrics data is not delivered to ServiceControl, and cannot be viewed in ServicePulse
* Log warnings stating `Failed to buffer metrics data for ${metricType} after ${attempts} attempts.`

## Who's affected

Some customers experience the symptoms listed above due to a non-deterministic execution order due to an unknown root cause. It is possible for some endpoints to be affected while others are not.

## Backporting

* Fixed in `master` branch by https://github.com/Particular/NServiceBus.Metrics.ServiceControl/pull/74
* Applied to 3.0.4 in https://github.com/Particular/NServiceBus.Metrics.ServiceControl/pull/75
* Backported to 2.1.3 via https://github.com/Particular/NServiceBus.Metrics.ServiceControl/pull/76

## Original report

The `ReportingFeature` feature has an implicit dependency on the `MetricsFeature` provided by the `NServiceBus.Metrics` package. However, this dependency is not expressed via the `DependsOn` API which can potentially cause these features to be used in a different orders.

While the `Setup` code is not directly dependent, the `FeatureStartupTasks` of the features are. The expected order of the feature setup and task start is the following:
1. Metrics Feature Setup: registers `SetupRegisteredObservers` startup task
2. ReportingFeature Setup: uses `options.RegisterObservers` API and registers the following (simplified) callback logic: `metrics = registerCallback.metrics`. It then passes `metrics` to the `ServiceControlRawDataReporting` startup task as a reference.
3. SetupRegisteredObservers.Start: it invokes all callbacks registered via `options.RegisterObservers`, including the logic mentioned in step 2.
4. ServiceControlRawDataReporting.Start: creates a "reporter" for for each metric and starts a reporting-task.

Because the order isn't actually guaranteed, this order can also happen:
1. ReportingFeature Setup: uses `options.RegisterObservers` API and registers the following (simplified) callback logic: `metrics = registerCallback.metrics`. It then passes `metrics` to the `ServiceControlRawDataReporting` startup task as a reference.
2. Metrics Feature Setup: registers `SetupRegisteredObservers` startup task
3. ServiceControlRawDataReporting.Start: creates a "reporter" for for each metric and starts a reporting-task. **the `metric` collection is empty here because the ServiceControlRawDataReporting.Start hasn't called the callback yet**
4. SetupRegisteredObservers.Start: it invokes all callbacks registered via `options.RegisterObservers`.

in this case, no reporters have been setup for the metrics. In the long run, this also causes the metrics buffer to be continuously filled without any consumer draining it, which also causes the following warnings in the log: `Failed to buffer metrics data for ${metricType} after ${attempts} attempts.`. At first glance, the logic which logs this warning in `RingBufferExtensions` also causes and infinite-loop. I did not further investigate this, but it looks like this could cause additional issues.

---
additional notes:
* I've tried to change the feature order by forcing `MetricsFeature` to be prioritized due to a `DependsOn` dependency from a custom feature. This does not solve the problem as this causes the `Setup` phase to execute in the right order (this is not a reliable approach anyway but I'm not going deeper on this right now) but it has no impact on the order of `FeatureStartupTasks`, this order is completely dependant on the orde of the scanned typed by the AssemblyScanner.
* I was able to reproduce this occasionally, I had specifically success when using `endpointConfiguration.AssemblyScanner().ScanAppDomainAssemblies = false;` as it has a chance of using a different order for the assembly-scanning process but it's by no means a reliable workaround.

**Comment by danielmarbach** [comment]
@WilliamBZA do you remember why at that time the `DependsOn` approach wasn't pursued? Is it because at that time there was no core version making sure startup tasks run in the correct order thus the workaround introduced as part of this work was the only way to go?

**Comment by WilliamBZA** [comment]
Ping @DavidBoike ☝️

**Comment by WilliamBZA** [comment]
@danielmarbach From the KTLO issue:

> I assumed that the solution was a simple DependsOn as hinted by Tim, but spent a good hour trying (unsuccessfully) to reproduce the problem, and couldn't. I tried preloading the NSB.Metrics.SC DLL before starting up the endpoint. I even tried to get fancy with a shell EXE preloading the NServiceBus.Metrics.ServiceControl DLL into its AppDomain, and THEN loading other assemblies for an endpoint, but I couldn't get the endpoint to start correctly in that instance, as NServiceBus REALLY wants to load from the BaseDirectory which didn't match what I was using.

**Comment by WilliamBZA** [comment]
And from https://github.com/Particular/NServiceBus.Metrics.ServiceControl/pull/72

> Not able to use DependsOn<T>() because MetricsFeature is internal.

**Comment by WilliamBZA** [comment]
And from @timbussmann in relation to a [DependsOn solution](https://github.com/Particular/NServiceBus.Metrics.ServiceControl/pull/73#issuecomment-554358546):

> I've tried to change the feature order by forcing MetricsFeature to be prioritized due to a DependsOn dependency from a custom feature. This does not solve the problem as this causes the Setup phase to execute in the right order (this is not a reliable approach anyway but I'm not going deeper on this right now) but it has no impact on the order of FeatureStartupTasks, this order is completely dependant on the orde of the scanned typed by the AssemblyScanner

**Comment by danielmarbach** [comment]
@WilliamBZA thanks for taking the time to answer.

> Not able to use DependsOn() because MetricsFeature is internal.

This is possible by using the string depends on the version. Not beautiful but it works. We are planning to make the feature public on the v4 version of the library

> I've tried to change the feature order by forcing MetricsFeature to be prioritized due to a DependsOn dependency from a custom feature. This does not solve the problem as this causes the Setup phase to execute in the right order (this is not a reliable approach anyway but I'm not going deeper on this right now) but it has no impact on the order of FeatureStartupTasks, this order is completely dependant on the orde of the scanned typed by the AssemblyScanner

FeatureStartupTasks are executed since 7.2.4 in the right order according to the dependency. @timbussmann do you remember what you meant with

> this is not a reliable approach anyway but I'm not going deeper on this right now)

Maybe we are missing something

> I assumed that the solution was a simple DependsOn as hinted by Tim, but spent a good hour trying (unsuccessfully) to reproduce the problem, and couldn't. I tried preloading the NSB.Metrics.SC DLL before starting up the endpoint. I even tried to get fancy with a shell EXE preloading the NServiceBus.Metrics.ServiceControl DLL into its AppDomain, and THEN loading other assemblies for an endpoint, but I couldn't get the endpoint to start correctly in that instance, as NServiceBus REALLY wants to load from the BaseDirectory which didn't match what I was using.

This one confuses me a bit. I get the testing challenges but I'm not sure if there is something in there that would make our approach a blocker

**Comment by WilliamBZA** [comment]
I think unfortunately this is a complex issue with over a year having passed, I don't remember much about it at all. Sorry I can't be more help.

**Comment by timbussmann** [comment]
@danielmarbach my comment was related to attempts to reliable reproduce the issue so that feature startup order changes. I used additional features in combination with DependsOn to try to change the order of the 2 metrics/metrics.servicecontrol features but that wasn't reliably working as it could be that it would keep the original order but run just both of them before my custom features. In addition there was the challenge of startup tasks not necessarily follow the features setup order.
